Use `boxen-install` for installing Casks
Whilst trying to install shortcat[1] via cask, I got the following
error:

```
==> sudo: no tty present and no askpass program specified
Error: /Stage[main]/Boxen::Personal/Package[shortcat]/ensure: change from absent to present failed: Execution of 'brew cask install shortcat --appdir=/Applications --binarydir=/opt/boxen/homebrew/bin' returned 1: Warning: Option --binarydir is obsolete!
Homebrew-Cask now uses the same location as your Homebrew installation for executable links.
==> Downloading https://files.shortcatapp.com/v0.7.7/Shortcat.zip
  Already downloaded:
  /Users/Jacob/Library/Caches/Homebrew/Cask/shortcat--0.7.7.zip
==> Verifying checksum for Cask shortcat
==> Moving App 'Shortcat.app' to '/Applications/Shortcat.app'.
==> Enabling accessibility access
Error: Command failed to execute!
```

This is because the application requires the user to input their
password however it times out waiting (since it's under Boxen). To
resolve this we can use `boxen-install` which among other things,
maintains your priviledged session and plugs in your sudo password when
needed.

The approach taken here is similar to `boxen/puppet-homebrew`[2].

[1]: https://shortcatapp.com
[2]: https://github.com/boxen/puppet-homebrew/blob/master/lib/puppet/provider/package/homebrew.rb#L60-L86